### ISSUE TITLE
I have a question, May I use another data?

### ISSUE THREAD

**Issue by Bao257** [Boulder-Investment-Technologies/lppls#72]
May I use another data instead of the data in nasdaq_dotcom.csv?

Traceback (most recent call last):
File "C:\Users\bao25\Desktop\lppls-master\use.py", line 14, in
time = [pd.Timestamp.toordinal(dt.strptime(t1, '%Y-%m-%d')) for t1 in data['Date']]
File "C:\Users\bao25\Desktop\lppls-master\use.py", line 14, in
time = [pd.Timestamp.toordinal(dt.strptime(t1, '%Y-%m-%d')) for t1 in data['Date']]
File "C:\Users\bao25\anaconda3\lib_strptime.py", line 568, in _strptime_datetime
tt, fraction, gmtoff_fraction = _strptime(data_string, format)
File "C:\Users\bao25\anaconda3\lib_strptime.py", line 349, in _strptime
raise ValueError("time data %r does not match format %r" %
ValueError: time data '1994/1/3' does not match format '%Y-%m-%d'

**Comment by Joshwani** [comment]
Hi @Bao257, yes you should be able to use your own data. Based on the error in your comment, I would try reformatting your date from '%Y/%m/%d' to '%Y-%m-%d'.
